### ISSUE TITLE
安卓的打印服务能否跳过预览直接打印？

### ISSUE THREAD

**Issue by yhao1012** [ILoveLin/PrinterDemo#2]
您好，首先感谢您的Demo分享，基于该示例我成功接入了安卓端的打印功能，不过目前每次打印都要先跳出预览与选择打印机的页面，体验不是很友好，想请教一下能否在已知打印机名称与纸张类型等参数的情况下跳过预览直接打印呢，期待您的答复！再次感谢！

**Comment by ILoveLin** [comment]
这个我就没研究了 不过我看应用市场很多打印的app都是需要先预览,在打印的,你自己可以查查资料
| |
tongzhengtong
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月16日 10:25 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [ILoveLin/PrinterDemo] 安卓的打印服务能否跳过预览直接打印？ (Issue #2) |

您好，首先感谢您的Demo分享，基于该示例我成功接入了安卓端的打印功能，不过目前每次打印都要先跳出预览与选择打印机的页面，体验不是很友好，想请教一下能否在已知打印机名称与纸张类型等参数的情况下跳过预览直接打印呢，期待您的答复！再次感谢！
